version: "3.8"

services:
  helpdeskmcpserver:
    build: .
    env_file:
      - .env
    environment:
      ENABLE_RATE_LIMITING: ${ENABLE_RATE_LIMITING:-true}
      ERROR_TRACKING_DSN: ${ERROR_TRACKING_DSN:-}
    ports:
      - "8008:8008"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/health"]
      interval: 30s
      timeout: 5s
      retries: 3
