version: "3.8"

services:
  helpdeskmcpserver:
    image: bbeeken/helpdeskmcpcerver:latest
    env_file:
      - .env
    ports:
      - "8008:8008"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/health"]
      interval: 30s
      timeout: 5s
      retries: 3
