version: "3.8"

services:
  helpdeskmcpserver:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # If you need to override or expose any ports:
    ports:
      - "8008:8008"
    # (Optional) healthcheck on your SQL Server connectivity:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
