version: '3.9'
services:
  postgres:
    image: postgres:16
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - demo

  helpdesk-api:
    build: .
    env_file: .env
    depends_on:
      - postgres
    networks: ['demo']
    ports:
      - "8000:8000"
    environment:
      DB_CONN_STRING: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}

volumes:
  postgres-data:

networks:
  demo:
