"""initial

Revision ID: 7bee13849318
Revises: 
Create Date: 2025-07-01 15:10:47.847027

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bee13849318'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Assets',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Label', sa.String(), nullable=True),
    sa.Column('Asset_Category_ID', sa.Integer(), nullable=True),
    sa.Column('Serial_Number', sa.String(), nullable=True),
    sa.Column('Model', sa.String(), nullable=True),
    sa.Column('Manufacturer', sa.String(), nullable=True),
    sa.Column('Site_ID', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Assets_ID'), 'Assets', ['ID'], unique=False)
    op.create_table('Sites',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Label', sa.String(), nullable=True),
    sa.Column('City', sa.String(), nullable=True),
    sa.Column('State', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Sites_ID'), 'Sites', ['ID'], unique=False)
    op.create_table('Ticket_Attachments',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Ticket_ID', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('WebURl', sa.String(), nullable=True),
    sa.Column('UploadDateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Ticket_Attachments_ID'), 'Ticket_Attachments', ['ID'], unique=False)
    op.create_table('Ticket_Categories',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Ticket_Categories_ID'), 'Ticket_Categories', ['ID'], unique=False)
    op.create_table('Ticket_Messages',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Ticket_ID', sa.Integer(), nullable=True),
    sa.Column('Message', sa.Text(), nullable=True),
    sa.Column('SenderUserCode', sa.String(), nullable=True),
    sa.Column('SenderUserName', sa.String(), nullable=True),
    sa.Column('DateTimeStamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Ticket_Messages_ID'), 'Ticket_Messages', ['ID'], unique=False)
    op.create_table('Ticket_Status',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Ticket_Status_ID'), 'Ticket_Status', ['ID'], unique=False)
    op.create_table('Tickets_Master',
    sa.Column('Ticket_ID', sa.Integer(), nullable=False),
    sa.Column('Subject', sa.String(), nullable=True),
    sa.Column('Ticket_Body', sa.Text(), nullable=True),
    sa.Column('Ticket_Status_ID', sa.Integer(), nullable=True),
    sa.Column('Ticket_Contact_Name', sa.String(), nullable=True),
    sa.Column('Ticket_Contact_Email', sa.String(), nullable=True),
    sa.Column('Asset_ID', sa.Integer(), nullable=True),
    sa.Column('Site_ID', sa.Integer(), nullable=True),
    sa.Column('Ticket_Category_ID', sa.Integer(), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Assigned_Name', sa.String(), nullable=True),
    sa.Column('Assigned_Email', sa.String(), nullable=True),
    sa.Column('Priority_ID', sa.Integer(), nullable=True),
    sa.Column('Assigned_Vendor_ID', sa.Integer(), nullable=True),
    sa.Column('Resolution', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Ticket_ID')
    )
    op.create_index(op.f('ix_Tickets_Master_Ticket_ID'), 'Tickets_Master', ['Ticket_ID'], unique=False)
    op.create_table('Vendors',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Site_ID', sa.Integer(), nullable=True),
    sa.Column('Asset_Category_ID', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Vendors_ID'), 'Vendors', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Vendors_ID'), table_name='Vendors')
    op.drop_table('Vendors')
    op.drop_index(op.f('ix_Tickets_Master_Ticket_ID'), table_name='Tickets_Master')
    op.drop_table('Tickets_Master')
    op.drop_index(op.f('ix_Ticket_Status_ID'), table_name='Ticket_Status')
    op.drop_table('Ticket_Status')
    op.drop_index(op.f('ix_Ticket_Messages_ID'), table_name='Ticket_Messages')
    op.drop_table('Ticket_Messages')
    op.drop_index(op.f('ix_Ticket_Categories_ID'), table_name='Ticket_Categories')
    op.drop_table('Ticket_Categories')
    op.drop_index(op.f('ix_Ticket_Attachments_ID'), table_name='Ticket_Attachments')
    op.drop_table('Ticket_Attachments')
    op.drop_index(op.f('ix_Sites_ID'), table_name='Sites')
    op.drop_table('Sites')
    op.drop_index(op.f('ix_Assets_ID'), table_name='Assets')
    op.drop_table('Assets')
    # ### end Alembic commands ###
