name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: pip install mypy
      - name: Start API and run smoke tests
        run: |
          uvicorn main:app --port 8000 &
          pid=$!
          sleep 5
          curl -f http://localhost:8000/health || curl -f http://localhost:8000/health/mcp
          echo '{"Subject":"Smoke","Ticket_Body":"check","Ticket_Contact_Name":"CI","Ticket_Contact_Email":"ci@example.com"}' | API_BASE_URL=http://localhost:8000 python tools/cli.py create-ticket
          kill $pid
      - run: mypy .
      - run: pytest -q
